#!/usr/bin/env bash
# Regenerates AGENTS.md and .github/copilot-instructions.md from
# docs/ai-guidance/CORE.md. Authoritative guidance lives under
# docs/ai-guidance/; this script only produces derived adapters.
#
# Usage:
#   scripts/sync-agent-guidance.sh            regenerate and overwrite adapters
#   scripts/sync-agent-guidance.sh --check    fail if committed adapters drift
#                                              from what CORE.md would generate
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
core_file="$repo_root/docs/ai-guidance/CORE.md"

if [[ ! -f "$core_file" ]]; then
  echo "error: $core_file not found" >&2
  exit 1
fi

tier2_files=(
  README.md
  PROJECT_GUIDANCE.md
  GOALS.md
  TENETS.md
  POLICIES.md
  ARCHITECTURE_RULES.md
  DEVELOPMENT_WORKFLOW.md
  TASK_WORKFLOW.md
)

# Rewrites bare "](FILENAME)" links from CORE.md so they resolve relative to
# the adapter's own location, then prints a full adapter file to stdout.
render_adapter() {
  local guidance_prefix="$1"
  local core_content
  core_content="$(cat "$core_file")"
  local f
  for f in "${tier2_files[@]}"; do
    core_content="${core_content//](${f})/](${guidance_prefix}${f})}"
  done

  cat <<EOF
<!--
GENERATED FILE — DO NOT EDIT BY HAND.
Generated by scripts/sync-agent-guidance.sh from ${guidance_prefix}CORE.md.
Authoritative guidance lives under docs/ai-guidance/. To change guidance,
edit ${guidance_prefix}CORE.md, then re-run scripts/sync-agent-guidance.sh
and commit the regenerated output.
-->

# Shared Project Guidance

${core_content}
EOF
}

check_mode=0
for arg in "$@"; do
  case "$arg" in
    --check) check_mode=1 ;;
    *)
      echo "error: unknown argument: $arg" >&2
      exit 1
      ;;
  esac
done

declare -A targets=(
  ["$repo_root/AGENTS.md"]="docs/ai-guidance/"
  ["$repo_root/.github/copilot-instructions.md"]="../docs/ai-guidance/"
)

drift=0
for target in "${!targets[@]}"; do
  prefix="${targets[$target]}"
  generated="$(render_adapter "$prefix")"

  if [[ "$check_mode" -eq 1 ]]; then
    if [[ ! -f "$target" ]]; then
      echo "drift: $target is missing" >&2
      drift=1
      continue
    fi
    if ! diff -u "$target" <(printf '%s\n' "$generated") >/dev/null; then
      echo "drift: $target does not match regeneration from CORE.md" >&2
      diff -u "$target" <(printf '%s\n' "$generated") >&2 || true
      drift=1
    fi
  else
    mkdir -p "$(dirname "$target")"
    printf '%s\n' "$generated" >"$target"
    echo "wrote $target"
  fi
done

if [[ "$check_mode" -eq 1 && "$drift" -ne 0 ]]; then
  echo "error: adapters are out of sync; run scripts/sync-agent-guidance.sh" >&2
  exit 1
fi

exit 0
